# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
#     - run: npm run build --if-present
#     - run: npx mocha      
    - run: npm install --no-save @testmo/testmo-cli
    
    # Optionally add a couple of fields such as the git hash and link to the build
    - run: |
        npx testmo automation:resources:add-field --name git --type string \
            --value ${GITHUB_SHA:0:7} --resources resources.json
          RUN_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          npx testmo automation:resources:add-link --name test \
            --url $RUN_URL --resources resources.json
            
    - run: |
          npx testmo automation:run:submit \
            --instance $TESTMO_URL \
            --project-id $1 \
            --name "Mocha test run" \
            --source "unit-tests" \
            --resources resources.json \
            --results results/*.xml \
            -- npm run mocha-junit # Note space after --
          env:
          TESTMO_URL: ${{secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{secrets.TESTMO_TOKEN }}
          id: run-tests
